export const LogBookList = 
[
  {
  key: '1', 
  Date: '01-01-2021',
  from: 'VOBL',
  to: 'VEBD',
  chocksOff: '00:48',
  chocksOn: '03:38',
  total: '02:50',
  aircraftType: '321',
  aircraftId: 'VTIUM',
  PICP1 : 'SELF',
  day: '02:50',
  night: '00:00',
  act: '00:00',
  sim: '00:00',
},
{
    key: '2', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '3', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '4', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '1', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '1', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '5', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '1', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '6', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '7', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '8', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '9', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
  {
    key: '10', 
    Date: '01-01-2021',
    from: 'VOBL',
    to: 'VEBD',
    chocksOff: '00:48',
    chocksOn: '03:38',
    total: '02:50',
    aircraftType: '321',
    aircraftId: 'VTIUM',
    PICP1 : 'SELF',
    day: '02:50',
    night: '00:00',
    act: '00:00',
    sim: '00:00',
  },
];

export const Places = 
[
  {
    id : '1',
    Code : 'NUP',
    Airport_name : 'internal Airport',
    city: 'Delhi',
  },
  {
    id : '2',
    Code : 'NUP1',
    Airport_name : 'internal Airport 1',
    city: 'Chandigarh',
  },
]

export const PeopleDummy = 
[
  {
    id : '1',
    name : 'NUPUR',
    Airline_code: 'SpiceJet',
    //city: 'Delhi',
  },
  {
    id : '2',
    name : 'NUPUR SHARMA',
    Airline_code : 'INDIGO',
    //city: 'Chandigarh',
  },
]

export const Precision = 
[
  {
    id : '1',
    PrecisionItem : 'GCA',
  },
  {
    id : '2',
    PrecisionItem : 'GPS/GNSS',
  },
  {
    id : '3',
    PrecisionItem : 'IGS',
  },
  {
    id : '4',
    PrecisionItem : 'ILS',
  },
  {
    id : '5',
    PrecisionItem : 'ILS-CAT2',
  },
  {
    id : '6',
    PrecisionItem : 'ILS-CAT3',
  },
  {
    id : '7',
    PrecisionItem : 'JPALS',
  },
  {
    id : '8',
    PrecisionItem : 'LAAS',
  },
  {
    id : '9',
    PrecisionItem : 'LPV',
  },
  {
    id : '10',
    PrecisionItem : 'MLS',
  },
  {
    id : '11',
    PrecisionItem : 'PAR',
  },
  {
    id : '12',
    PrecisionItem : 'WAAS',
  },
]

export const NonPrecision = 
[
  {
    id : '1',
    nonPrecisionItem : 'ARA',
  },
  {
    id : '2',
    nonPrecisionItem : 'DME',
  },
  {
    id : '3',
    nonPrecisionItem : 'GPS',
  },
  {
    id : '4',
    nonPrecisionItem : 'IAN',
  },
  {
    id : '5',
    nonPrecisionItem : 'LDA',
  },
  {
    id : '6',
    nonPrecisionItem : 'LNAV',
  },
  {
    id : '7',
    nonPrecisionItem : 'LOC',
  },
  {
    id : '8',
    nonPrecisionItem : 'LOC BC',
  },
  {
    id : '9',
    nonPrecisionItem : 'LOC/DME',
  },
  {
    id : '10',
    nonPrecisionItem : 'LP',
  },
  {
    id : '11',
    nonPrecisionItem : 'NDB',
  },
  {
    id : '12',
    nonPrecisionItem : 'RNAV',
  },
  {
    id : '13',
    nonPrecisionItem : 'RNP',
  },
  {
    id : '14',
    nonPrecisionItem : 'SDF',
  },
  {
    id : '15',
    nonPrecisionItem : 'SRA',
  },
  {
    id : '16',
    nonPrecisionItem : 'TACAN',
  },
  {
    id : '17',
    nonPrecisionItem : 'VISUAL',
  },
  {
    id : '18',
    nonPrecisionItem : 'VOR',
  },
  {
    id : '19',
    nonPrecisionItem : 'VOR/DME',
  },
]